export * from "~/sanity/queries/authors"
export * from "~/sanity/queries/categories"
export * from "~/sanity/queries/partners"
export * from "~/sanity/queries/posts"
export * from "~/sanity/queries/subCategories"
export * from "~/sanity/queries/tags"
